[versions]
core = "1.8.0"
coil = "2.1.0"

[libraries]
kotlin-android-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }


[bundles]
retrofit-deps = ["kotlin-android-ktx"]